# Generated by Django 5.1.3 on 2025-01-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transactionhistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='bucket',
            field=models.CharField(choices=[('C', 'Capital'), ('P', 'Interest')], default='C', max_length=1),
        ),
    ]
